
import '../app/globals.css'
import { Montserrat } from 'next/font/google'
import { UserProvider } from './_context/authContext'

const Monste = Montserrat({
  subsets: ['latin'],
  preload: true,
  display: 'swap',
  variable: '--font-inter'
})


export const metadata = {
  title: 'HELLO CHAT',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Monste.variable} font-sans`}>
        <UserProvider>{children}</UserProvider>
        </body>
    </html>
  )
}
